site_name: pystac-user
repo_url: https://github.com/WolodjaZ/jax-vqgan

theme:
  name: "material"

plugins:
  - search
  # - mike
  - markdown-exec
  - mkdocstrings

nav:
  - Welcome to Docs ğŸ‘‹: index.md
  - Changelog â³: changelog.md

# extra:
#   version:
#     provider: mike

watch:
  - src  # reload docs for any file changes
